### ISSUE TITLE
Console Warning - Running Vue in development mode

### ISSUE THREAD

**Issue by sutcliffe121** [mydnic/laravel-feedback-component#103]
Hello,

I am using the latest version of the package but I am seeing a warning in console about running Vue in dev mode:

You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

Can the package be update to use production version?

Thanks,

**Comment by mydnic** [comment]
Sorry about that, I haven't worked on it for a while. Will publish in a few minutes

**Comment by mydnic** [comment]
Done ! You can update to 1.6.1
