### ISSUE TITLE
You are running Vue in development mode.

### ISSUE THREAD

**Issue by guratr** [mydnic/laravel-feedback-component#66]
HI. I noticed that public/js/kustomer.js file size is **1.22 MB**, which is huge for production. 
Probably because you used development build. There is warning in console 

> You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

Could you please make prod version of js and css files. Minification would be great to.

**Comment by mydnic** [comment]
@guratr you're right

I've just published v1.5.2 with a production build

Let me know if there's anything else
