### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by mafudelaptu** [mydnic/laravel-feedback-component#70]
Hello,

im running Laravel v7. i have added the script in head section and the include statement in body tag

onload im getting the js error in console:

`TypeError: Cannot read property 'title' of undefined`

am i missing something? Thank for help :)

**Comment by mafudelaptu** [comment]
after some invastigation, this error happening if i uncomment in config/kustomer.php in feedback array the bug section

**Comment by mydnic** [comment]
@mafudelaptu you have to uncomment the bug section in the lang file as well I think :) 
https://github.com/mydnic/laravel-feedback-component/blob/master/resources/lang/en/kustomer.php#L82

Tell me if that fixes the problem
